import { prisma } from '@fluid/database';
import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import JSZip from 'jszip';

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 80);
}

function generateFrontmatter(page: { title: string; description: string | null; slug: string; createdAt: Date; updatedAt: Date }): string {
  const fields: string[] = ['---'];
  fields.push(`title: "${page.title.replace(/"/g, '\\"')}"`);
  fields.push(`slug: "${page.slug}"`);
  if (page.description) {
    fields.push(`description: "${page.description.replace(/"/g, '\\"')}"`);
  }
  fields.push(`created_at: ${page.createdAt.toISOString()}`);
  fields.push(`updated_at: ${page.updatedAt.toISOString()}`);
  fields.push('---');
  return fields.join('\n');
}

type PageNode = { id: string; title: string; slug: string; order: number; parentId: string | null; description: string | null; published: boolean; content: string; createdAt: Date; updatedAt: Date; projectId: string };
type PageNodeBasic = Pick<PageNode, 'id' | 'title' | 'slug' | 'order' | 'parentId' | 'description'>;

function buildTree(pages: PageNodeBasic[]): string {
  const map = new Map<string, PageNodeBasic[]>();
  const roots: PageNodeBasic[] = [];

  for (const page of pages) {
    if (!page.parentId) {
      roots.push(page);
    } else {
      const existing = map.get(page.parentId) || [];
      existing.push(page);
      map.set(page.parentId, existing);
    }
  }

  function renderBranch(page: PageNodeBasic, depth: number): string {
    const children = map.get(page.id) || [];
    const indent = '  '.repeat(depth);
    let result = `${indent}- [${page.title}](./${slugify(page.title)}.md)`;
    if (page.description) {
      result += ` — ${page.description}`;
    }
    result += '\n';
    for (const child of children) {
      result += renderBranch(child, depth + 1);
    }
    return result;
  }

  return roots.map((r) => renderBranch(r, 0)).join('');
}

function generatePageContent(page: { title: string; content: string }, projectName: string): string {
  const content = page.content.replace(/^---[\s\S]*?---\n*/g, '');
  return `<div align="center">

*${projectName} documentation*

---

</div>

${content}

---

<div align="center">
  <sub>Generated by <a href="https://usedocs.com">Fluid</a></sub>
</div>
`;
}

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;

    const project = await prisma.project.findFirst({
      where: {
        id,
        team: { members: { some: { userId: session.user.id } } },
      },
    });
    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const pages = await prisma.docPage.findMany({
      where: { projectId: id },
      orderBy: [{ order: 'asc' }],
    });

    const zip = new JSZip();
    const today = new Date().toISOString().split('T')[0];
    const projectSlug = slugify(project.name);

    // Generate README
    const readmeSections: string[] = [];

    if (project.logoUrl) {
      readmeSections.push(`<div align="center">
  <img src="${project.logoUrl}" alt="${project.name} logo" height="80" />
</div>\n`);
    }

    readmeSections.push(`# ${project.name}\n`);

    if (project.description) {
      readmeSections.push(`> ${project.description}\n`);
    }

    readmeSections.push(`<div align="center">

[![Generated by Fluid](https://img.shields.io/badge/Generated%20by-Fluid-0c8ee7)](https://usedocs.com)
![Pages](https://img.shields.io/badge/Pages-${pages.length}-green)
![Exported](https://img.shields.io/badge/Exported-${today}-lightgrey)

</div>\n`);

    if (pages.length > 0) {
      readmeSections.push('## Table of Contents\n');
      readmeSections.push(buildTree(pages));
      readmeSections.push('');
    }

    const publishedCount = pages.filter((p) => p.published).length;
    readmeSections.push('---\n');
    readmeSections.push(`| Total Pages | Published | Drafts | Exported |`);
    readmeSections.push(`|------------:|----------:|------:|---------:|`);
    readmeSections.push(`| ${pages.length} | ${publishedCount} | ${pages.length - publishedCount} | ${today} |`);
    readmeSections.push('');

    readmeSections.push(`<div align="center">
  <sub>Exported from <a href="https://usedocs.com">Fluid</a> — Knowledge that flows into action.</sub>
</div>`);

    zip.file('README.md', readmeSections.join('\n'));

    for (const page of pages) {
      const frontmatter = generateFrontmatter(page);
      const filename = `${slugify(page.title)}.md`;
      const body = generatePageContent(page, project.name);
      zip.file(filename, `${frontmatter}\n\n${body}`);
    }

    const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${projectSlug}-docs.zip`,
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Failed to export project' }, { status: 500 });
  }
}
