import { prisma } from '@fluid/database';
import { NextResponse } from 'next/server';
import { auth } from '@/lib/auth';
import JSZip from 'jszip';

type ExportFormat = 'markdown' | 'html' | 'json' | 'rst' | 'asciidoc';

function slugify(str: string): string {
  return str
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
    .slice(0, 80);
}

function escapeHtml(str: string): string {
  return str.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function mdToSimpleHtml(md: string): string {
  let html = escapeHtml(md);
  html = html.replace(/^### (.+)$/gm, '<h3>$1</h3>');
  html = html.replace(/^## (.+)$/gm, '<h2>$1</h2>');
  html = html.replace(/^# (.+)$/gm, '<h1>$1</h1>');
  html = html.replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>');
  html = html.replace(/\*(.+?)\*/g, '<em>$1</em>');
  html = html.replace(/`([^`]+)`/g, '<code>$1</code>');
  html = html.replace(/^- (.+)$/gm, '<li>$1</li>');
  html = html.replace(/\n\n/g, '</p><p>');
  return `<p>${html}</p>`;
}

function generateFrontmatter(page: { title: string; description: string | null; slug: string; createdAt: Date; updatedAt: Date }): string {
  const fields: string[] = ['---'];
  fields.push(`title: "${page.title.replace(/"/g, '\\"')}"`);
  fields.push(`slug: "${page.slug}"`);
  if (page.description) {
    fields.push(`description: "${page.description.replace(/"/g, '\\"')}"`);
  }
  fields.push(`created_at: ${page.createdAt.toISOString()}`);
  fields.push(`updated_at: ${page.updatedAt.toISOString()}`);
  fields.push('---');
  return fields.join('\n');
}

type PageNode = { id: string; title: string; slug: string; order: number; parentId: string | null; description: string | null; published: boolean; content: string; createdAt: Date; updatedAt: Date; projectId: string };
type PageNodeBasic = Pick<PageNode, 'id' | 'title' | 'slug' | 'order' | 'parentId' | 'description'>;

function buildTree(pages: PageNodeBasic[], ext: string): string {
  const map = new Map<string, PageNodeBasic[]>();
  const roots: PageNodeBasic[] = [];

  for (const page of pages) {
    if (!page.parentId) {
      roots.push(page);
    } else {
      const existing = map.get(page.parentId) || [];
      existing.push(page);
      map.set(page.parentId, existing);
    }
  }

  function renderBranch(page: PageNodeBasic, depth: number): string {
    const children = map.get(page.id) || [];
    const indent = '  '.repeat(depth);
    let result = `${indent}- [${page.title}](./${slugify(page.title)}.${ext})`;
    if (page.description) {
      result += ` — ${page.description}`;
    }
    result += '\n';
    for (const child of children) {
      result += renderBranch(child, depth + 1);
    }
    return result;
  }

  return roots.map((r) => renderBranch(r, 0)).join('');
}

function generateMarkdownPage(page: { title: string; content: string }, projectName: string): string {
  const content = page.content.replace(/^---[\s\S]*?---\n*/g, '');
  return `<div align="center">\n\n*${projectName} documentation*\n\n---\n\n</div>\n\n${content}\n\n---\n\n<div align="center">\n  <sub>Generated by <a href="https://tomebase.io">TomeBase</a></sub>\n</div>`;
}

function generateRstPage(page: { title: string; content: string }): string {
  const lines = [
    page.title,
    '='.repeat(page.title.length),
    '',
    page.content.replace(/^---[\s\S]*?---\n*/g, ''),
    '',
    '..',
    '   Generated by TomeBase (https://tomebase.io)',
  ];
  return lines.join('\n');
}

function generateAsciiDocPage(page: { title: string; content: string }): string {
  const lines = [
    `= ${page.title}`,
    '',
    page.content.replace(/^---[\s\S]*?---\n*/g, ''),
    '',
    '---',
    '_Generated by https://tomebase.io[TomeBase]_',
  ];
  return lines.join('\n');
}

function generateHtmlPage(page: { title: string; content: string }, projectName: string): string {
  const body = page.content.replace(/^---[\s\S]*?---\n*/g, '');
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(page.title)} — ${escapeHtml(projectName)}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 800px; margin: 0 auto; padding: 2rem; line-height: 1.6; color: #333; }
    h1 { border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5rem; }
    h2 { margin-top: 2rem; }
    code { background: #f3f4f6; padding: 0.15rem 0.35rem; border-radius: 4px; font-size: 0.9em; }
    pre { background: #1f2937; color: #e5e7eb; padding: 1rem; border-radius: 8px; overflow-x: auto; }
    pre code { background: none; color: inherit; padding: 0; }
    blockquote { border-left: 4px solid #3b82f6; margin: 1rem 0; padding: 0.5rem 1rem; background: #eff6ff; }
    table { border-collapse: collapse; width: 100%; margin: 1rem 0; }
    th, td { border: 1px solid #e5e7eb; padding: 0.5rem 1rem; text-align: left; }
    th { background: #f9fafb; }
    .footer { text-align: center; margin-top: 3rem; padding-top: 1rem; border-top: 1px solid #e5e7eb; color: #9ca3af; font-size: 0.85rem; }
    a { color: #2563eb; }
  </style>
</head>
<body>
  <div class="header" style="text-align:center; margin-bottom: 2rem; color: #6b7280;">
    <em>${escapeHtml(projectName)} documentation</em>
  </div>
  ${mdToSimpleHtml(body)}
  <div class="footer">
    <p>Generated by <a href="https://tomebase.io">TomeBase</a></p>
  </div>
</body>
</html>`;
}

function generateJsonProject(project: { name: string; description: string | null }, pages: PageNode[]): object {
  return {
    name: project.name,
    description: project.description,
    exportedAt: new Date().toISOString(),
    generator: 'TomeBase',
    url: 'https://tomebase.io',
    pages: pages.map((p) => ({
      title: p.title,
      slug: p.slug,
      description: p.description,
      published: p.published,
      content: p.content.replace(/^---[\s\S]*?---\n*/g, ''),
      createdAt: p.createdAt.toISOString(),
      updatedAt: p.updatedAt.toISOString(),
    })),
  };
}

export async function GET(
  request: Request,
  { params }: { params: Promise<{ id: string }> },
) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { id } = await params;

    const url = new URL(request.url);
    const format = (url.searchParams.get('format') || 'markdown') as ExportFormat;

    const project = await prisma.project.findFirst({
      where: {
        id,
        team: { members: { some: { userId: session.user.id } } },
      },
    });
    if (!project) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 });
    }

    const pages = await prisma.docPage.findMany({
      where: { projectId: id },
      orderBy: [{ order: 'asc' }],
    });

    const today = new Date().toISOString().split('T')[0];
    const projectSlug = slugify(project.name);

    if (format === 'json') {
      const data = generateJsonProject(project, pages);
      return NextResponse.json(data, {
        headers: {
          'Content-Disposition': `attachment; filename="${projectSlug}-docs.json"`,
        },
      });
    }

    const zip = new JSZip();
    const ext = format === 'html' ? 'html' : format === 'rst' ? 'rst' : format === 'asciidoc' ? 'adoc' : 'md';

    // Generate index/README
    if (format === 'markdown') {
      const readmeSections: string[] = [];
      if (project.logoUrl) {
        readmeSections.push(`<div align="center">\n  <img src="${project.logoUrl}" alt="${project.name} logo" height="80" />\n</div>\n`);
      }
      readmeSections.push(`# ${project.name}\n`);
      if (project.description) {
        readmeSections.push(`> ${project.description}\n`);
      }
      readmeSections.push(`<div align="center">\n\n[![Generated by TomeBase](https://img.shields.io/badge/Generated%20by-TomeBase-0c8ee7)](https://tomebase.io)\n![Pages](https://img.shields.io/badge/Pages-${pages.length}-green)\n![Exported](https://img.shields.io/badge/Exported-${today}-lightgrey)\n\n</div>\n`);
      if (pages.length > 0) {
        readmeSections.push('## Table of Contents\n');
        readmeSections.push(buildTree(pages, 'md'));
        readmeSections.push('');
      }
      const publishedCount = pages.filter((p) => p.published).length;
      readmeSections.push('---\n');
      readmeSections.push(`| Total Pages | Published | Drafts | Exported |`);
      readmeSections.push(`|------------:|----------:|------:|---------:|`);
      readmeSections.push(`| ${pages.length} | ${publishedCount} | ${pages.length - publishedCount} | ${today} |`);
      readmeSections.push('');
      readmeSections.push(`<div align="center">\n  <sub>Exported from <a href="https://tomebase.io">TomeBase</a> — Your knowledge base.</sub>\n</div>`);
      zip.file('README.md', readmeSections.join('\n'));
    } else if (format === 'html') {
      // Index page
      const tocItems = pages.map((p) => `        <li><a href="${slugify(p.title)}.html">${escapeHtml(p.title)}</a></li>`).join('\n');
      zip.file('index.html', `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escapeHtml(project.name)} — Documentation</title>
  <style>body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,sans-serif;max-width:800px;margin:0 auto;padding:2rem;line-height:1.6;color:#333}a{color:#2563eb}h1{border-bottom:2px solid #e5e7eb;padding-bottom:.5rem}.footer{text-align:center;margin-top:3rem;padding-top:1rem;border-top:1px solid #e5e7eb;color:#9ca3af;font-size:.85rem}ul{padding-left:1.5rem}li{margin:.4rem 0}</style>
</head>
<body>
  <h1>${escapeHtml(project.name)}</h1>
  ${project.description ? `<p>${escapeHtml(project.description)}</p>` : ''}
  <p><strong>Table of Contents</strong></p>
  <ul>
${tocItems}
  </ul>
  <p style="color:#6b7280;font-size:.85em">${pages.length} pages · Exported ${today}</p>
  <div class="footer"><p>Generated by <a href="https://tomebase.io">TomeBase</a></p></div>
</body>
</html>`);
    } else if (format === 'rst') {
      const tocItems = pages.map((p) => `   ${slugify(p.title).replace(/-/g, '_')}.rst   ${p.title}`).join('\n');
      zip.file('index.rst', `${project.name}
${'='.repeat(project.name.length)}

${project.description || ''}

.. toctree::
   :maxdepth: 2
   :caption: Contents:

${tocItems}

---
Generated by TomeBase (https://tomebase.io)
`);
    } else if (format === 'asciidoc') {
      const tocItems = pages.map((p) => `* xref:${slugify(p.title)}[${p.title}]`).join('\n');
      zip.file('index.adoc', `= ${project.name}

${project.description || ''}

== Table of Contents

${tocItems}

---
_Exported ${today} from https://tomebase.io[TomeBase]_
`);
    }

    // Generate page files
    for (const page of pages) {
      const filename = `${slugify(page.title)}.${ext}`;

      if (format === 'markdown') {
        const frontmatter = generateFrontmatter(page);
        const body = generateMarkdownPage(page, project.name);
        zip.file(filename, `${frontmatter}\n\n${body}`);
      } else if (format === 'html') {
        zip.file(filename, generateHtmlPage(page, project.name));
      } else if (format === 'rst') {
        zip.file(filename, generateRstPage(page));
      } else if (format === 'asciidoc') {
        zip.file(filename, generateAsciiDocPage(page));
      }
    }

    const buffer = await zip.generateAsync({ type: 'nodebuffer', compression: 'DEFLATE' });

    return new NextResponse(new Uint8Array(buffer), {
      headers: {
        'Content-Type': 'application/zip',
        'Content-Disposition': `attachment; filename="${projectSlug}-docs.zip"`,
      },
    });
  } catch (error) {
    console.error('Export error:', error);
    return NextResponse.json({ error: 'Failed to export project' }, { status: 500 });
  }
}
